services:
  - type: web
    name: fastapi-langchain
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        value: fromRender
      - key: MONGODB_URI
        value: fromRender
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: fromRender